//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MapEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TOOLBAR1                    201
#define IDB_TREE_FOLDER                 203
#define IDB_TREE_CLP                    204
#define IDB_TREE_EXP                    205
#define IDD_EXPORT                      206
#define IDD_NEWMAP                      207
#define IDD_EDIT_HERO                   208
#define IDD_PROPS_GUARD                 209
#define IDR_BRUSH_SIZ                   210
#define IDB_MAINTB24                    212
#define IDR_SURF_TYPE                   215
#define IDB_SURFTB24                    217
#define IDD_PROPS_MINERAL               218
#define IDD_CHILD_ARMY                  219
#define IDD_PAGE_ARMY                   219
#define IDD_PAGE_MESSAGE                220
#define IDD_PAGE_GEN_MINERAL            221
#define IDD_PAGE_GEN_GUARD              222
#define IDD_PAGE_GEN_OWNCNST            223
#define IDD_PAGE_GEN_CASTLE             224
#define IDD_MSPAGE_GENERAL              225
#define IDD_MSPAGE_PLAYERS              226
#define IDD_PAGE_GEN_HERO               227
#define IDD_PAGE_HERO_SKILLS            228
#define IDD_PAGE_CTL_CNSTS              229
#define IDD_PAGE_SPELLBOOK              230
#define IDD_SPELL_LIST                  231
#define IDD_PAGE_GEN_SPELLSCROLL        232
#define IDD_MAP_VALIDATE                233
#define IDD_PLAYER_INFO                 234
#define IDD_PAGE_TIME_EVENTS            235
#define IDD_TIME_EVENT                  236
#define IDD_PAGE_GEN_MAPEVENT           237
#define IDD_PAGE_REWARDS                238
#define IDD_REWARD_TYPE                 239
#define IDD_REW_MINERAL                 240
#define IDD_REW_EXPERIENCE              241
#define IDD_REW_MANAPTS                 242
#define IDD_REW_TRAVELPTS               243
#define IDD_REW_MORALE                  244
#define IDD_REW_LUCK                    245
#define IDD_REW_FURTSKILL               246
#define IDD_REW_SPELL                   247
#define IDD_REW_ARTIFACT                248
#define IDD_REW_CREATGROUP              249
#define IDD_ULTIMATE_ART                250
#define IDD_MAPTEXT                     251
#define IDD_TEXTEDIT                    252
#define IDD_MSPAGE_LANGS                253
#define IDC_SIZE_SMALL                  1000
#define IDC_SIZE_MEDIUM                 1001
#define IDC_SIZE_LARGE                  1002
#define IDC_SIZE_EXTRALARGE             1003
#define IDC_PLAYER1                     1004
#define IDC_PLAYER2                     1005
#define IDC_PLAYER3                     1006
#define IDC_PLAYER4                     1007
#define IDC_PLAYER5                     1008
#define IDC_PLAYER6                     1009
#define IDC_TYPE_PLAYER1                1010
#define IDC_TYPE_PLAYER2                1011
#define IDC_TYPE_PLAYER3                1012
#define IDC_TYPE_PLAYER4                1013
#define IDC_TYPE_PLAYER5                1014
#define IDC_TYPE_PLAYER6                1015
#define IDC_EDIT1                       1016
#define IDC_COMBO1                      1017
#define IDC_MAP_NAME                    1018
#define IDC_MAP_SIZE                    1019
#define IDC_MAP_VERSION                 1019
#define IDC_GEN_LSCAPE                  1020
#define IDC_MAP_AUTHOR                  1020
#define IDC_LOG                         1021
#define IDC_RADIO_QUANTITY_RANDOM       1022
#define IDC_RADIO_QUANTITY_CUSTOM       1023
#define IDC_QUANTITY_UPDOWN             1024
#define IDC_EDIT_QUANTITY               1025
#define IDC_CHECK_QUANTITY_NOTGROW      1026
#define IDC_SLOT1_CRTYPE                1030
#define IDC_SLOT2_CRTYPE                1031
#define IDC_SLOT3_CRTYPE                1032
#define IDC_SLOT4_CRTYPE                1033
#define IDC_SLOT5_CRTYPE                1034
#define IDC_SLOT6_CRTYPE                1035
#define IDC_SLOT7_CRTYPE                1036
#define IDC_CUSTOMIZE_CHECK             1037
#define IDC_MSG_EDIT                    1038
#define IDC_SK_CUSTOMIZE_CHECK          1038
#define IDC_ATTACKMSG_EDIT              1039
#define IDC_SLOT1_QUANTED               1040
#define IDC_SLOT2_QUANTED               1041
#define IDC_SLOT3_QUANTED               1042
#define IDC_SLOT4_QUANTED               1043
#define IDC_SLOT5_QUANTED               1044
#define IDC_SLOT6_QUANTED               1045
#define IDC_MT_STATIC                   1045
#define IDC_SLOT7_QUANTED               1046
#define IDC_NOTGROW                     1046
#define IDC_DISP01                      1047
#define IDC_DISP02                      1048
#define IDC_DISP03                      1049
#define IDC_NEVERFLEES                  1050
#define IDC_SLOT1_QUANTSP               1050
#define IDC_CT_STATIC                   1051
#define IDC_SLOT2_QUANTSP               1051
#define IDC_SLOT3_QUANTSP               1052
#define IDC_SLOT4_QUANTSP               1053
#define IDC_SLOT5_QUANTSP               1054
#define IDC_SLOT6_QUANTSP               1055
#define IDC_CUSTOMIZE_EDIT              1055
#define IDC_SLOT7_QUANTSP               1056
#define IDC_EXPRES                      1056
#define IDC_LANGCB                      1057
#define IDC_ENCRYPTION                  1057
#define IDC_DIFFICULTY                  1059
#define IDC_RADIO_RANDOM                1060
#define IDC_DESCRIPTION                 1060
#define IDC_RADIO_CUSTOM                1061
#define IDC_MAP_FILENAME                1061
#define IDC_QUANTITY_EDIT               1062
#define IDC_QUANTITY_SPIN               1063
#define IDC_CNST_LIST                   1065
#define IDC_BUILT                       1066
#define IDC_ADD                         1067
#define IDC_REMOVE                      1068
#define IDC_RESET                       1069
#define IDC_SPELL_LIST                  1070
#define IDC_SKILL_TYPE1                 1071
#define IDC_ADDALL                      1071
#define IDC_SKILL_TYPE2                 1072
#define IDC_SPELL_COMBO                 1072
#define IDC_SKILL_TYPE3                 1073
#define IDC_REPORT                      1073
#define IDC_SKILL_TYPE4                 1074
#define IDC_SKILL_TYPE5                 1075
#define IDC_SKILL_TYPE6                 1076
#define IDC_CREATE_HERO                 1076
#define IDC_SKILL_TYPE7                 1077
#define IDC_CTL_LIST                    1077
#define IDC_SKILL_TYPE8                 1078
#define IDC_EVENT_LIST                  1078
#define IDC_ADD_EVENT                   1079
#define IDC_EDIT_EVENT                  1080
#define IDC_SKILL_LEVEL1                1081
#define IDC_DELETE_EVENT                1081
#define IDC_SKILL_LEVEL2                1082
#define IDC_DELETE_ALL_EVENTS           1082
#define IDC_EDIT2                       1082
#define IDC_EVENT_TEXT                  1082
#define IDC_SKILL_LEVEL3                1083
#define IDC_SKILL_LEVEL4                1084
#define IDC_SKILL_LEVEL5                1085
#define IDC_EVENT_NAME                  1085
#define IDC_SKILL_LEVEL6                1086
#define IDC_SKILL_LEVEL7                1087
#define IDC_REPEAT_COMBO                1087
#define IDC_SKILL_LEVEL8                1088
#define IDC_REWARDS_LIST                1088
#define IDC_MIN_TYPE                    1090
#define IDC_PRSKILL_EDIT1               1091
#define IDC_MINERAL_QUANTED             1091
#define IDC_PRSKILL_EDIT2               1092
#define IDC_MINERAL_QUANTSP             1092
#define IDC_PRSKILL_EDIT3               1093
#define IDC_QUANTED                     1093
#define IDC_PRSKILL_EDIT4               1094
#define IDC_QUANTSP                     1094
#define IDC_PRSKILL_SPIN1               1095
#define IDC_PRSKILL_SPIN2               1096
#define IDC_PRSKILL_SPIN3               1097
#define IDC_PRSKILL_SPIN4               1098
#define IDC_TAB1                        1100
#define IDC_SKILL_TYPE                  1101
#define IDC_SKILL_VALED                 1102
#define IDC_SKILL_VALSP                 1103
#define IDC_REWARDMSG_EDIT              1104
#define IDC_ARTIFACT_LIST               1105
#define IDC_CREAT_QUANTED               1106
#define IDC_CREAT_QUANTSP               1107
#define IDC_CREAT_TYPE                  1108
#define IDC_RADIUS_ED                   1109
#define IDC_RADIUS_SP                   1110
#define IDC_SETTINGS_PLAYER1            1111
#define IDC_TEXTRES_LIST                1111
#define IDC_SETTINGS_PLAYER2            1112
#define IDC_SETTINGS_PLAYER3            1113
#define IDC_TEXT                        1113
#define IDC_SETTINGS_PLAYER4            1114
#define IDC_LNGLIST                     1114
#define IDC_ORIG_TEXT                   1114
#define IDC_SETTINGS_PLAYER5            1115
#define IDC_SETTINGS_PLAYER6            1116
#define IDC_MINERAL1_QUANTED            1121
#define IDC_MINERAL2_QUANTED            1122
#define IDC_MINERAL3_QUANTED            1123
#define IDC_MINERAL4_QUANTED            1124
#define IDC_MINERAL5_QUANTED            1125
#define IDC_MINERAL6_QUANTED            1126
#define IDC_MINERAL7_QUANTED            1127
#define IDC_FTIME_EDIT                  1128
#define IDC_MINERAL1_QUANTSP            1131
#define IDC_MINERAL2_QUANTSP            1132
#define IDC_MINERAL3_QUANTSP            1133
#define IDC_MINERAL4_QUANTSP            1134
#define IDC_MINERAL5_QUANTSP            1135
#define IDC_MINERAL6_QUANTSP            1136
#define IDC_MINERAL7_QUANTSP            1137
#define IDC_FTIME_SPAN                  1138
#define IDC_EDITBTN                     1150
#define IDC_REWARDT_1                   1201
#define IDC_REWARDT_2                   1202
#define IDC_REWARDT_3                   1203
#define IDC_REWARDT_4                   1204
#define IDC_REWARDT_5                   1205
#define IDC_REWARDT_6                   1206
#define IDC_REWARDT_7                   1207
#define IDC_REWARDT_8                   1208
#define IDC_REWARDT_9                   1209
#define IDC_REWARDT_10                  1210
#define IDC_LNG_ENG_01                  1301
#define IDC_LNG_RUS_02                  1302
#define IDC_LNG_POL_03                  1303
#define IDC_LNG_SLV_04                  1304
#define IDC_LNG_GER_05                  1305
#define IDC_LNG_CZE_06                  1306
#define IDC_LNG_ITA_07                  1307
#define IDC_LNG_FRN_08                  1308
#define IDC_LNG_SPN_09                  1309
#define ID_BUTTON32772                  32772
#define ID_BUTTON32773                  32773
#define IDC_SHOW_GRID                   32774
#define ID_VIEW_GRID                    32774
#define IDC_SHOW_SHADOWS                32775
#define ID_VIEW_SHADOWS                 32775
#define ID_EXPORT_DATA                  32776
#define ID_TOOL_EDIT                    32777
#define ID_TOOL_SURFACE                 32778
#define ID_TOOL_CREATE                  32779
#define ID_TOOL_ERASE                   32780
#define ID_VIEW_PASSMAP                 32784
#define ID_BRUSH01                      32791
#define ID_BRUSH02                      32792
#define ID_BRUSH03                      32793
#define ID_BRUSH04                      32794
#define ID_BRUSH05                      32795
#define ID_PLAYER_NEUTRAL               32800
#define ID_PLAYER1                      32801
#define ID_PLAYER2                      32802
#define ID_PLAYER3                      32803
#define ID_PLAYER4                      32804
#define ID_PLAYER5                      32805
#define ID_PLAYER6                      32806
#define ID_TOOLS_MAPSPEC                32807
#define ID_FILE_SAVEAS                  32808
#define ID_TOOLS_VALIDATE               32809
#define ID_MAPTEXT                      32813
#define ID_BATCH_EXPORT                 32814
#define ID_ERASE                        32815
#define ID_SURFACE                      32817
#define ID_VIEW_RID                     32818
#define ID_SURF_UP                      32832
#define ID_SURF_DOWN                    32833
#define ID_SURF_WATER                   32900
#define ID_SURF_SAND                    32901
#define ID_SURF_DIRT                    32902
#define ID_SURF_GRASS                   32903
#define ID_SURF_SWAMP                   32904
#define ID_SURF_LAVA                    32905
#define ID_SURF_WASTELAND               32906
#define ID_SURF_DESERT                  32907
#define ID_SURF_SNOW                    32908
#define ID_SURF_NDESERT                 32909
#define ID_SURF_COBBLES1                32910
#define ID_SURF_COBBLES2                32911

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        253
#define _APS_NEXT_COMMAND_VALUE         32835
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
