#ifndef _CONSTANT_SOUNDS_DEFINITIONS_H_
#define _CONSTANT_SOUNDS_DEFINITIONS_H_

// This file is automatically generated by Pocket Heroes resource compiler.
// Do not modify this file -- YOUR CHANGES WILL BE ERASED!

const sint16                   CSND_PREBATTLE = 0;
const sint16                   CSND_QUEST_DLG = 1;
const sint16               CSND_NEW_LEVEL_DLG = 2;
const sint16                    CSND_TREASURE = 3;
const sint16                   CSND_FLAG_MINE = 4;
const sint16                      CSND_BUTTON = 5;
const sint16                         CSND_DIG = 6;
const sint16                     CSND_SEAWASH = 7;
const sint16                    CSND_PICKUP01 = 8;
const sint16                    CSND_PICKUP02 = 9;
const sint16                    CSND_PICKUP03 = 10;
const sint16                    CSND_PICKUP04 = 11;
const sint16                    CSND_PICKUP05 = 12;
const sint16                   CSND_DEL_GUARD = 13;
const sint16                CSND_TELEPORT_OUT = 14;
const sint16                     CSND_HMOVE01 = 15;
const sint16                     CSND_HMOVE02 = 16;
const sint16                     CSND_HMOVE03 = 17;
const sint16                     CSND_HMOVE04 = 18;
const sint16                     CSND_HMOVE05 = 19;
const sint16                     CSND_HMOVE06 = 20;
const sint16                    CSND_ALCH_LAB = 21;
const sint16                     CSND_SAWMILL = 22;
const sint16                        CSND_MINE = 23;
const sint16                      CSND_SHRINE = 24;
const sint16                     CSND_STABLES = 25;
const sint16                     CSND_VOLCANO = 26;
const sint16                       CSND_LAKES = 27;
const sint16                    CSND_TELEPORT = 28;
const sint16                       CSND_ARENA = 29;
const sint16                  CSND_BLACKSMITH = 30;
const sint16                  CSND_HYDRA_POND = 31;
const sint16                 CSND_MARKETPLACE = 32;
const sint16                 CSND_ARCHERS_HUT = 33;
const sint16               CSND_HAUNTED_HOUSE = 34;

#endif //_CONSTANT_SOUNDS_DEFINITIONS_H_
